Repository wecode-bootcamp-korea/37-2nd-skyski-frontend, pull requests merged in 2022-10, with the labels that each got.

#2 [37기 안나라]Add: header 레이아웃 완료
  src/components/Header/Header.js
Labels: 멘토 리뷰 요청

#1 [37기 성종화] ADD : footer 수정사항 반영 및 구현완료
  src/components/Footer/Footer.js
  src/components/Footer/TEXT_FOUR.js
  src/components/Footer/TEXT_ONE.js
  src/components/Footer/TEXT_THREE.js
  src/components/Footer/TEXT_TWO.js
Labels: 멘토 리뷰 요청

#3 monthly 리뷰반영
  package-lock.json
  package.json
  public/images/1624940829950_0.jpeg
  public/images/IMG_1167.jpg
  public/images/IMG_1168.jpg
  public/images/cantaloupe-g887f4a6ff_1280.png
  public/images/images.jpeg
  public/images/logo(melon).png
  public/images/나이키 로고.png
  public/images/스크린샷 2022-10-05 오후 8.37.48.png
  src/pages/Monthly/Monthly.js
Labels: 수정 요청

#4 [37기 안나라] Add: Login 모달 레이아웃 구현완료, 추가 기능 구현중
  .gitignore
  package-lock.json
  package.json
  public/images/travel.png
  src/Router.js
  src/components/Login/LoginForm.js
  src/components/Login/RedirectKakao.js
Labels: 멘토 리뷰 요청

#5 Monthly 페이지 구현완료.
  public/data/Mock/Mock.json
  public/data/Mock/Mock2.json
  public/images/LOGO_ZINWOOS.png
  public/images/images (1).jpeg
  src/pages/Monthly/DailyPay.js
  src/pages/Monthly/DropBox.js
  src/pages/Monthly/Maping.js
  src/pages/Monthly/Monthly.js
Labels: 도움 요청, 멘토 리뷰 요청

#7 [37기 안나라]Add: header 로그인여부에 따른 버튼상태 변화
  .env
  src/components/Header/Header.js
Labels: 멘토 리뷰 요청

#8 [37기 안나라] Modify: Login 오류 수정
  package-lock.json
  src/components/Login/RedirectKakao.js
Labels: 완료

#9 monthly페이지 최종의 최종
  package-lock.json
  public/data/Mock/Mock.json
  public/data/Mock/Mock2.json
  src/pages/Monthly/Maping.js
  src/pages/Monthly/Monthly.js
Labels: 멘토 리뷰 요청
